<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150310212635 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE hfrahmann_todolist_domain_model_category (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE hfrahmann_todolist_domain_model_todo (persistence_object_identifier VARCHAR(40) NOT NULL, category VARCHAR(40) DEFAULT NULL, done TINYINT(1) NOT NULL DEFAULT '0', title VARCHAR(255) NOT NULL, content VARCHAR(255) NOT NULL, creationdate DATETIME NOT NULL, INDEX IDX_9A9A386764C19C1 (category), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE hfrahmann_todolist_domain_model_todo ADD CONSTRAINT FK_9A9A386764C19C1 FOREIGN KEY (category) REFERENCES hfrahmann_todolist_domain_model_category (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE hfrahmann_todolist_domain_model_todo DROP FOREIGN KEY FK_9A9A386764C19C1");
		$this->addSql("DROP TABLE hfrahmann_todolist_domain_model_category");
		$this->addSql("DROP TABLE hfrahmann_todolist_domain_model_todo");
	}
}